places=["pakistan", "america", "iran", "japan", "china"]
print(places)
print(sorted(places))
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.reverse()
print(places)
